spring:
  cloud:
    config:
      server:
        git:
          url: https://github.com/jesusmiguelgarciaduran/SpringBootcamp-configServer.git
          default-label: main
          search-paths:
          - '*service'